version: "3"
services:
  server:
    build:
      context: ./web
      dockerfile: prod.Dockerfile
    image: student-net:prod
    ports:
      - "80:3000" # (Usually we expose port 80 to the rest of the internet.)
    depends_on:
      - db
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root-prod
      MYSQL_DATABASE: studentnet-prod
    ports:
      - "3306:3306"
